// services/e2eeAutomation.js - HOÀN CHỈNH
const crypto = require("crypto");
const User = require("../models/user");
const Room = require("../models/room");
const Message = require("../models/message");

console.log("🤖 [e2eeAutomation] Service loaded successfully");

class E2EEAutomationService {
  constructor() {
    this.autoKeyRotationInterval = 24 * 60 * 60 * 1000; // 24 giờ
    this.keyRotationTimers = new Map();
    this.init();
  }

  /**
   * Khởi tạo service
   */
  async init() {
    console.log("🤖 [e2eeAutomation] Initializing E2EE automation service");

    // Tự động enable E2EE cho tất cả users khi khởi động
    await this.autoEnableE2EEForAllUsers();

    // Bắt đầu key rotation schedule
    this.startKeyRotationSchedule();

    console.log("✅ [e2eeAutomation] Service initialized successfully");
  }

  /**
   * Tự động enable E2EE cho tất cả users
   */
  async autoEnableE2EEForAllUsers() {
    try {
      console.log("🤖 [e2eeAutomation] Auto-enabling E2EE for all users...");

      const users = await User.find({ e2eeEnabled: { $ne: true } });

      for (const user of users) {
        try {
          await this.autoGenerateKeysForUser(user.keycloakId);
          console.log(`✅ Auto-enabled E2EE for user: ${user.username}`);
        } catch (error) {
          console.error(
            `❌ Failed to auto-enable E2EE for ${user.username}:`,
            error.message
          );
        }
      }

      console.log(`✅ Auto-enabled E2EE for ${users.length} users`);
    } catch (error) {
      console.error("❌ [autoEnableE2EEForAllUsers] Error:", error);
    }
  }

  /**
   * Tự động generate keys cho user
   */
  async autoGenerateKeysForUser(keycloakId) {
    try {
      console.log(
        `🤖 [autoGenerateKeysForUser] Generating keys for user: ${keycloakId}`
      );

      const user = await User.findOne({ keycloakId });
      if (!user) {
        throw new Error("User not found");
      }

      // Tạo key pair tự động
      const keyPair = this.generateKeyPairAutomatically();

      // Thêm key vào user
      const newKey = {
        publicKey: keyPair.publicKey,
        keyType: "ecdh-p256",
        fingerprint: this.calculateKeyFingerprint(keyPair.publicKey),
        createdAt: new Date(),
        isActive: true,
        isAutoGenerated: true,
        autoGeneratedAt: new Date(),
      };

      // Đánh dấu tất cả keys cũ là không active
      if (user.e2eeKeys && user.e2eeKeys.length > 0) {
        user.e2eeKeys.forEach((key) => {
          key.isActive = false;
        });
      }

      // Thêm key mới
      user.e2eeKeys = user.e2eeKeys || [];
      user.e2eeKeys.push(newKey);
      user.currentKeyId = newKey.fingerprint;
      user.e2eeEnabled = true;
      user.autoE2EEEnabled = true;
      user.lastKeyRotation = new Date();

      await user.save();

      // Lưu private key tạm thời (trong thực tế cần lưu an toàn)
      await this.storeTemporaryPrivateKey(
        keycloakId,
        keyPair.privateKey,
        newKey.fingerprint
      );

      console.log(
        `✅ Auto-generated keys for user: ${user.username}, fingerprint: ${newKey.fingerprint}`
      );

      return {
        success: true,
        fingerprint: newKey.fingerprint,
        keyType: newKey.keyType,
        publicKey: newKey.publicKey,
      };
    } catch (error) {
      console.error(
        `❌ [autoGenerateKeysForUser] Error for ${keycloakId}:`,
        error
      );
      throw error;
    }
  }

  /**
   * Tạo key pair tự động
   */
  generateKeyPairAutomatically() {
    const ecdh = crypto.createECDH("prime256v1");
    ecdh.generateKeys();

    return {
      publicKey: ecdh.getPublicKey("base64"),
      privateKey: ecdh.getPrivateKey("base64"),
      algorithm: "ECDH",
      curve: "prime256v1",
    };
  }

  /**
   * Tính fingerprint
   */
  calculateKeyFingerprint(publicKey) {
    return crypto
      .createHash("sha256")
      .update(publicKey)
      .digest("hex")
      .substring(0, 8)
      .toUpperCase();
  }

  /**
   * Lưu private key tạm thời (DEMO ONLY - không dùng production)
   */
  async storeTemporaryPrivateKey(userId, privateKey, fingerprint) {
    // Trong thực tế, private key nên được lưu ở client-side hoặc HSM
    // Đây chỉ là demo để minh họa
    const tempStorage = {
      userId,
      fingerprint,
      privateKey,
      storedAt: new Date(),
      expiresAt: new Date(Date.now() + 5 * 60 * 1000), // 5 phút
    };

    console.log(`⚠️ TEMP private key stored for ${userId} (expires in 5 mins)`);
    // Trong thực tế: gửi private key qua secure channel đến client
  }

  /**
   * Tự động rotate keys theo lịch
   */
  startKeyRotationSchedule() {
    console.log("🔄 [e2eeAutomation] Starting automatic key rotation schedule");

    // Rotate keys mỗi 24 giờ
    setInterval(async () => {
      try {
        await this.rotateKeysForAllUsers();
      } catch (error) {
        console.error("❌ [Key Rotation Schedule] Error:", error);
      }
    }, this.autoKeyRotationInterval);
  }

  /**
   * Rotate keys cho tất cả users
   */
  async rotateKeysForAllUsers() {
    try {
      console.log("🔄 [rotateKeysForAllUsers] Starting key rotation...");

      const users = await User.find({
        e2eeEnabled: true,
        autoE2EEEnabled: true,
      });

      let rotatedCount = 0;
      let failedCount = 0;

      for (const user of users) {
        try {
          // Kiểm tra nếu đã rotate trong 24 giờ qua
          if (
            user.lastKeyRotation &&
            Date.now() - user.lastKeyRotation.getTime() <
              this.autoKeyRotationInterval
          ) {
            continue;
          }

          await this.rotateUserKey(user.keycloakId);
          rotatedCount++;
        } catch (error) {
          console.error(
            `❌ Failed to rotate key for ${user.username}:`,
            error.message
          );
          failedCount++;
        }
      }

      console.log(
        `✅ Key rotation completed: ${rotatedCount} rotated, ${failedCount} failed`
      );
    } catch (error) {
      console.error("❌ [rotateKeysForAllUsers] Error:", error);
    }
  }

  /**
   * Rotate key cho một user cụ thể
   */
  async rotateUserKey(keycloakId) {
    try {
      console.log(`🔄 [rotateUserKey] Rotating key for user: ${keycloakId}`);

      const user = await User.findOne({ keycloakId });
      if (!user || !user.e2eeEnabled) {
        throw new Error("User not found or E2EE not enabled");
      }

      // Tạo key mới
      const keyPair = this.generateKeyPairAutomatically();

      // Revoke key cũ
      const currentKey = user.e2eeKeys.find(
        (k) => k.fingerprint === user.currentKeyId
      );
      if (currentKey) {
        currentKey.isActive = false;
        currentKey.isRevoked = true;
        currentKey.revokedAt = new Date();
        currentKey.revokedReason = "automatic_rotation";
      }

      // Thêm key mới
      const newKey = {
        publicKey: keyPair.publicKey,
        keyType: "ecdh-p256",
        fingerprint: this.calculateKeyFingerprint(keyPair.publicKey),
        createdAt: new Date(),
        isActive: true,
        isAutoGenerated: true,
        autoGeneratedAt: new Date(),
        rotationNumber: (user.e2eeKeys?.length || 0) + 1,
      };

      user.e2eeKeys.push(newKey);
      user.currentKeyId = newKey.fingerprint;
      user.lastKeyRotation = new Date();

      await user.save();

      // Lưu private key tạm thời
      await this.storeTemporaryPrivateKey(
        keycloakId,
        keyPair.privateKey,
        newKey.fingerprint
      );

      // Thông báo cho friends về key mới
      await this.notifyFriendsAboutKeyRotation(user);

      console.log(
        `✅ Key rotated for user: ${user.username}, new fingerprint: ${newKey.fingerprint}`
      );

      return {
        success: true,
        oldFingerprint: currentKey?.fingerprint,
        newFingerprint: newKey.fingerprint,
        rotationTime: new Date(),
      };
    } catch (error) {
      console.error(`❌ [rotateUserKey] Error for ${keycloakId}:`, error);
      throw error;
    }
  }

  /**
   * Thông báo cho friends về key rotation
   */
  async notifyFriendsAboutKeyRotation(user) {
    try {
      if (!user.friends || user.friends.length === 0) {
        return;
      }

      const currentKey = user.e2eeKeys.find(
        (k) => k.fingerprint === user.currentKeyId
      );

      // Trong thực tế sẽ gửi socket event
      console.log(
        `📢 Notifying ${user.friends.length} friends about key rotation for ${user.username}`
      );

      // Log cho debug
      user.friends.forEach((friendId) => {
        console.log(
          `   → Friend: ${friendId}, New key: ${currentKey.fingerprint}`
        );
      });
    } catch (error) {
      console.error(`❌ [notifyFriendsAboutKeyRotation] Error:`, error);
    }
  }

  /**
   * Tự động thiết lập E2EE cho room mới
   */
  async autoSetupE2EEForRoom(roomId, creatorId) {
    try {
      console.log(
        `🤖 [autoSetupE2EEForRoom] Setting up E2EE for room: ${roomId}`
      );

      const room = await Room.findById(roomId);
      if (!room) {
        throw new Error("Room not found");
      }

      // Enable E2EE cho room
      room.e2eeEnabled = true;
      room.e2eeAutoSetup = true;
      room.e2eeSetupBy = creatorId;
      room.e2eeSetupAt = new Date();

      // Đảm bảo tất cả members có E2EE enabled
      for (const memberId of room.members) {
        try {
          const member = await User.findOne({ keycloakId: memberId });
          if (member && !member.e2eeEnabled) {
            await this.autoGenerateKeysForUser(memberId);
            console.log(
              `✅ Auto-enabled E2EE for room member: ${member.username}`
            );
          }
        } catch (error) {
          console.error(
            `❌ Failed to auto-enable E2EE for member ${memberId}:`,
            error.message
          );
        }
      }

      await room.save();

      console.log(`✅ Auto-setup E2EE for room: ${room.name}`);

      return {
        success: true,
        roomId: room._id,
        roomName: room.name,
        e2eeEnabled: true,
        membersWithE2EE: room.members.length,
      };
    } catch (error) {
      console.error(
        `❌ [autoSetupE2EEForRoom] Error for room ${roomId}:`,
        error
      );
      throw error;
    }
  }

  /**
   * Tự động exchange keys giữa hai users
   */
  async autoExchangeKeys(user1Id, user2Id) {
    try {
      console.log(
        `🤝 [autoExchangeKeys] Auto exchanging keys between ${user1Id} and ${user2Id}`
      );

      const [user1, user2] = await Promise.all([
        User.findOne({ keycloakId: user1Id }),
        User.findOne({ keycloakId: user2Id }),
      ]);

      if (!user1 || !user2) {
        throw new Error("One or both users not found");
      }

      // Đảm bảo cả hai đều có E2EE enabled
      if (!user1.e2eeEnabled) {
        await this.autoGenerateKeysForUser(user1Id);
      }
      if (!user2.e2eeEnabled) {
        await this.autoGenerateKeysForUser(user2Id);
      }

      // Lấy public keys
      const user1Key = user1.e2eeKeys.find(
        (k) => k.fingerprint === user1.currentKeyId
      );
      const user2Key = user2.e2eeKeys.find(
        (k) => k.fingerprint === user2.currentKeyId
      );

      if (!user1Key || !user2Key) {
        throw new Error("One or both users don't have active keys");
      }

      // Tạo exchange record (trong thực tế có thể lưu vào database)
      const exchangeId = this.generateExchangeId(user1Id, user2Id);

      const exchangeRecord = {
        exchangeId,
        user1: user1Id,
        user2: user2Id,
        user1Key: user1Key.fingerprint,
        user2Key: user2Key.fingerprint,
        exchangedAt: new Date(),
        status: "completed",
        isAutoExchange: true,
      };

      console.log(`✅ Auto key exchange completed: ${exchangeId}`);

      return {
        success: true,
        exchangeId,
        user1: {
          id: user1Id,
          keyFingerprint: user1Key.fingerprint,
        },
        user2: {
          id: user2Id,
          keyFingerprint: user2Key.fingerprint,
        },
        exchangedAt: new Date(),
      };
    } catch (error) {
      console.error(`❌ [autoExchangeKeys] Error:`, error);
      throw error;
    }
  }

  /**
   * Tạo exchange ID
   */
  generateExchangeId(user1Id, user2Id) {
    const ids = [user1Id, user2Id].sort();
    return crypto
      .createHash("md5")
      .update(ids.join("|"))
      .digest("hex")
      .substring(0, 12)
      .toUpperCase();
  }

  /**
   * Tự động mã hóa tin nhắn
   */
  async autoEncryptMessage(senderId, roomId, plaintext) {
    try {
      console.log(
        `🔐 [autoEncryptMessage] Auto encrypting message for room: ${roomId}`
      );

      const room = await Room.findById(roomId);
      if (!room || !room.e2eeEnabled) {
        throw new Error("Room not found or E2EE not enabled");
      }

      // Lấy sender's current key
      const sender = await User.findOne({ keycloakId: senderId });
      if (!sender || !sender.e2eeEnabled) {
        throw new Error("Sender not found or E2EE not enabled");
      }

      const senderKey = sender.e2eeKeys.find(
        (k) => k.fingerprint === sender.currentKeyId
      );
      if (!senderKey) {
        throw new Error("Sender doesn't have active key");
      }

      // Tạo encryption key ngẫu nhiên (trong thực tế sẽ dùng shared secret)
      const encryptionKey = crypto.randomBytes(32); // 256-bit key
      const iv = crypto.randomBytes(12); // 96-bit IV cho AES-GCM

      // Mã hóa tin nhắn
      const cipher = crypto.createCipheriv("aes-256-gcm", encryptionKey, iv);
      let encrypted = cipher.update(plaintext, "utf8", "base64");
      encrypted += cipher.final("base64");
      const authTag = cipher.getAuthTag();

      // Tạo encrypted message object
      const encryptedMessage = {
        ciphertext: encrypted,
        iv: iv.toString("base64"),
        keyId: senderKey.fingerprint,
        algorithm: "AES-GCM-256",
        authTag: authTag.toString("base64"),
        encryptedAt: new Date(),
        senderKeyFingerprint: senderKey.fingerprint,
        isAutoEncrypted: true,
      };

      console.log(
        `✅ Message auto-encrypted, ciphertext length: ${encrypted.length}`
      );

      return {
        success: true,
        encryptedData: encryptedMessage,
        originalLength: plaintext.length,
        encryptedLength: encrypted.length,
      };
    } catch (error) {
      console.error(`❌ [autoEncryptMessage] Error:`, error);
      throw error;
    }
  }

  /**
   * Tự động đồng bộ keys cho tất cả users
   */
  async syncAllUsersKeys() {
    try {
      console.log("🔄 [syncAllUsersKeys] Syncing keys for all users...");

      const users = await User.find({ e2eeEnabled: true });

      const syncReport = {
        totalUsers: users.length,
        synced: 0,
        failed: 0,
        details: [],
      };

      for (const user of users) {
        try {
          // Kiểm tra và fix keys nếu cần
          await this.validateAndFixUserKeys(user);
          syncReport.synced++;
          syncReport.details.push({
            userId: user.keycloakId,
            username: user.username,
            status: "synced",
            activeKey: user.currentKeyId,
          });
        } catch (error) {
          syncReport.failed++;
          syncReport.details.push({
            userId: user.keycloakId,
            username: user.username,
            status: "failed",
            error: error.message,
          });
        }
      }

      console.log(
        `✅ Keys sync completed: ${syncReport.synced} synced, ${syncReport.failed} failed`
      );

      return syncReport;
    } catch (error) {
      console.error("❌ [syncAllUsersKeys] Error:", error);
      throw error;
    }
  }

  /**
   * Validate và fix user keys nếu cần
   */
  async validateAndFixUserKeys(user) {
    const issues = [];

    // Kiểm tra có active key không
    const activeKey = user.e2eeKeys?.find((k) => k.isActive);
    if (!activeKey) {
      issues.push("No active key found");
      // Tự động tạo key mới
      await this.autoGenerateKeysForUser(user.keycloakId);
    }

    // Kiểm tra currentKeyId có match với active key không
    if (
      user.currentKeyId &&
      activeKey &&
      user.currentKeyId !== activeKey.fingerprint
    ) {
      issues.push("currentKeyId doesn't match active key");
      user.currentKeyId = activeKey.fingerprint;
    }

    // Kiểm tra có nhiều hơn 1 active key không
    const activeKeys = user.e2eeKeys?.filter((k) => k.isActive) || [];
    if (activeKeys.length > 1) {
      issues.push(`Multiple active keys found: ${activeKeys.length}`);
      // Chỉ giữ lại key mới nhất
      const latestActiveKey = activeKeys.sort(
        (a, b) => b.createdAt - a.createdAt
      )[0];
      activeKeys.forEach((key) => {
        if (key.fingerprint !== latestActiveKey.fingerprint) {
          key.isActive = false;
        }
      });
    }

    if (issues.length > 0) {
      console.log(`⚠️ Fixed issues for ${user.username}:`, issues);
      await user.save();
    }

    return {
      hadIssues: issues.length > 0,
      issues,
      fixed: issues.length,
    };
  }

  /**
   * Get automation status
   */
  async getAutomationStatus() {
    const totalUsers = await User.countDocuments();
    const e2eeEnabledUsers = await User.countDocuments({ e2eeEnabled: true });
    const autoEnabledUsers = await User.countDocuments({
      autoE2EEEnabled: true,
    });

    const roomsWithE2EE = await Room.countDocuments({ e2eeEnabled: true });
    const totalRooms = await Room.countDocuments();

    const lastSync = await User.findOne({ e2eeEnabled: true })
      .sort({ lastKeyRotation: -1 })
      .select("lastKeyRotation");

    return {
      automation: {
        serviceRunning: true,
        startedAt: new Date(),
        uptime: process.uptime(),
      },
      users: {
        total: totalUsers,
        e2eeEnabled: e2eeEnabledUsers,
        autoEnabled: autoEnabledUsers,
        percentage:
          totalUsers > 0
            ? ((e2eeEnabledUsers / totalUsers) * 100).toFixed(1) + "%"
            : "0%",
      },
      rooms: {
        total: totalRooms,
        e2eeEnabled: roomsWithE2EE,
        percentage:
          totalRooms > 0
            ? ((roomsWithE2EE / totalRooms) * 100).toFixed(1) + "%"
            : "0%",
      },
      keyRotation: {
        interval: this.autoKeyRotationInterval,
        lastRotation: lastSync?.lastKeyRotation || null,
      },
    };
  }
}

// Tạo singleton instance
const e2eeAutomationService = new E2EEAutomationService();

module.exports = e2eeAutomationService;
